`Toggle` 컴포넌트 추가
Team-Crops/fit-web pull request #14
Opened 2023-12-27 13:29 UTC by jaewoongs

### 변경 개요
`Toggle` 컴포넌트를 추가했습니다!

### 구현 내용
<img width="549" alt="image" src="https://github.com/Team-Crops/fit-web/assets/58589176/1dd78e30-1245-4cac-9edb-34560ea2e546">

`Toggle` on/off 구현했습니다.

### 관련 이슈
#6

2023-12-28 17:43 UTC, seheon99 requested changes
소수점 픽셀까지 신경써서 그런지 엄청 깔끔하고 자연스러운 것 같아요!!

그런데 코드를 보면서 `onChange` 이벤트를 예상했는데 `onClick` 이벤트가 있어서 조금 의아했습니다

`input`과 같은 다른 입력받는 컴포넌트와 비슷하게 동작하면 좋겠다는 생각에 P2 리뷰로 남겼는데 확인 부탁드립니다!

2023-12-28 17:43 UTC, seheon99 commented on src/components/atoms/Toggle.tsx
> +};
P1: `input` 이나 `select`, `textarea` 를 사용할 때처럼 `onChange` 로 `checked` 값이 바뀔 때 실행할 콜백함수를 등록하는게 자연스럽다고 생각합니다! `onClick` 으로 클릭 이벤트 핸들러를 등록하신 이유가 있나요??

2023-12-30 05:34 UTC, jaewoongs commented on src/components/atoms/Toggle.tsx
> +};
click으로 이벤트가 발생해서 직관적으로 `onClick`으로 작성했는데 세헌님 말씀대로 `onChange` 가 더 좋을 것 같네요! 수정해서 올리겠습니다!!

2023-12-31 11:19 UTC, seheon99 approved these changes
수고하셨습니다!!

2024-01-02 07:08 UTC, merged