마이페이지 버그 수정
Team-Crops/fit-web pull request #170
Opened 2024-06-18 06:10 UTC by jaewoongs

### 변경 개요
피드백 나온 마이페이지 버그 수정

### 구현 내용
- 마이페이지 초기 기술 스택 보여주기
- 학력/경력 입력 시 글자 초과 에러 수정
- 포트폴리오 링크 아이콘 제대로 안나오는 버그 수정
- 학교/회사에 따라 placeholder 바뀌게 수정
- 링크 입력 시 빈 url 입력 불가능하게 수정

### 관련 이슈
resolved: #144 #145 #146 #147 #154

2024-06-18 07:24 UTC, seheon99 requested changes

2024-06-18 07:24 UTC, seheon99 commented on src/components/molecules/MyPage/TechSelectBlock.tsx
> +  initPosition?: number;
P4: 이름은 포지션인데 타입이 넘버라 모호한 면이 있는 것 같아요. `initPositionId` 나 `initPosition?: Position['id']` 는 어때요?

2024-06-18 07:24 UTC, seheon99 commented on src/components/molecules/MyPage/TechSelectBlock.tsx
> +
P2: `useState` 에 넣어서 `selectedPosition` 값을 `initPosition` 으로 초기화하는게 좋아보이는데 그러지 않은 이유가 있나요??

```ts
const [selectedPosition, setSelectedPosition] = useState(initPosition ?? 0)
```

2024-06-19 11:02 UTC, jaewoongs commented on src/components/molecules/MyPage/TechSelectBlock.tsx
> +  initPosition?: number;
둘 다 좋은 의견같아서 둘다 적용하겠습니다!

2024-06-19 11:03 UTC, jaewoongs commented on src/components/molecules/MyPage/TechSelectBlock.tsx
> +
이 방법을 생각하지 못했습니다 수정하겠습니다!!

2024-06-19 11:07 UTC, seheon99 approved these changes

2024-06-19 11:07 UTC, merged