팀원 추천 페이지 버그 수정
Team-Crops/fit-web pull request #183
Opened 2024-06-22 05:36 UTC by jaewoongs

### 변경 개요
피드백 나온 팀원추천 페이지 버그 수정

### 구현 내용
- 전체가 기본으로 선택되게 수정
- 포트폴리오 링크 클릭 시 새로운 창에서 열리게 수정
- 로딩이 계속 떠 있는 버그 수정

### 관련 이슈
resolved: #153 #155 #156 #158

2024-06-22 10:50 UTC, seheon99 requested changes

2024-06-22 10:50 UTC, seheon99 commented on src/types/link.ts
> +export interface LinkList {
P2: 배열이 아닌 타입 이름이 `List` 인게 많이 어색하게 느껴져요! `next/link` 이름과 겹쳐서 바꾸게 된거라면 `next/link` 를 `NextLink` 로 가져오는건 어떤가요??

```js
import NextLink from 'next/link`;
import { Link } from '#/types';
```

2024-06-22 10:50 UTC, seheon99 commented on src/types/link.ts
> +  isPortfolio?: boolean;
P2: `isPortfolio` 대신 `LinkType` 에 `'PORTFOLIO'` 로 추가하는건 어때요? `isPortfolio` 가 `true` 일 때 `linkType` 값은 의미없어지는게 아닌가 싶어서!

2024-06-22 10:50 UTC, seheon99 commented on src/components/templates/TeamRecommend/UserCardList.tsx
> +        {isLoading && <Loading ref={observerRef} />}
P1: `observerRef` 객체가 담겨있어서 `isLoading` 일 때 보여주면 다음 페이지 로딩이 안될 것 같아요! `isLoading` 이 아니라 `hasNext` 가 맞지 않나요??

2024-06-22 10:50 UTC, seheon99 commented on src/components/templates/TeamRecommend.tsx
> +      {users && (
P4: 처음 유저 쿼리할 때 빈 칸보다 로딩 중 화면을 보여주면 좋을 것 같은데 아래처럼 하는건 어떤가여

```ts
return users ? <UserCardList /> : <Loading />
```

2024-06-22 10:50 UTC, seheon99 commented on src/components/organisms/UserDetails.tsx
> +                  linkUrl: process.env.NEXT_PUBLIC_STORAGE_URL + user?.portfolioUrl ?? '',
P1: 이렇게 바꿔도 좋을 것 같아요

```ts
{
  ...
  linkUrl: process.env.NEXT_PUBLIC_STORAGE_URL + user.portfolioUrl,
}
```

2024-06-22 16:35 UTC, jaewoongs commented on src/components/templates/TeamRecommend.tsx
> +      {users && (
여기에 Loading을 추가하면 `userCardList` 안에 있는 Loading 이랑 겹칠 것 같은데 어떤가요??

2024-06-23 04:09 UTC, seheon99 commented on src/components/templates/TeamRecommend.tsx
> +      {users && (
아 그러네!!

2024-06-23 04:09 UTC, seheon99 approved these changes

2024-06-23 04:09 UTC, merged