Feature Home Page
Team-Crops/fit-web pull request #35
Opened 2024-01-28 06:41 UTC by jaewoongs

### 변경 개요
메인 페이지 제작

### 구현 내용
- `<Header />` 제작
- `<Txt />`에 필요한 크기(50px, 48px) 추가
- Home page 제작

### 추가할 내용
- 로그인 여부에 따른 Header 변경
- 애니메이션 추가
- Swiper 이슈 해결

### 관련 이슈
resolved: #16

2024-02-01 09:57 UTC, seheon99 requested changes
수고하셨습니다!!

- P4: `public/img` 에서 `public/images` 로 바꿔도 될까요?

2024-02-01 09:57 UTC, seheon99 commented on src/components/atoms/FitLogo.tsx
> +      viewBox={`0 0 ${width} ${(width * 38) / 119}`}
P1: `width` 값을 키워도 정상적으로 표시되나요? `width` 가 지금의 코드에서는 로고가 아닌 이미지의 배경 너비만 조절하는 것처럼 보입니다

P3: `<Icons />` 처럼 SVG 이미지는 별도 파일로 관리하고 `@svgr/webpack` 을 통해 불러오는게 어떤가요?

2024-02-01 09:57 UTC, seheon99 commented on src/components/organisms/HeaderContent.tsx
> +        {/* <HeaderNonLoginBlock /> */}
P1: 주석!

2024-02-01 09:57 UTC, seheon99 commented on src/components/templates/Header.tsx
> +      <HeaderShadow />
P3: `<HeaderShadow />` 이름 자체로 해더 뒤에서 공간을 차지한다는 느낌이 드는데 주석을 지우는건 어떤가요? 아니면 다음 방법도 좋을 것 같아요

```javascript
const SpaceCSS = css`
	width: 100%;
	height: 100px;
`;

const StyledHeader = styled.header`
	...
	{SpaceCSS}
`;

const HeaderSpacer = styled.div`
	{SpaceCSS}
`;
```

2024-02-01 09:57 UTC, seheon99 commented on src/assets/icons/account.svg
> +<svg width="45" height="51" viewBox="0 0 45 51" fill="none"
P1: `width="current" height="current"`가 빠졌어요

2024-02-02 08:19 UTC, jaewoongs commented on src/components/templates/Header.tsx
> +      <HeaderShadow />
좋은 의견인것같아요!! 수정하겠습니다

2024-02-02 08:25 UTC, jaewoongs commented
> 수고하셨습니다!!
> 
> * P4: `public/img` 에서 `public/images` 로 바꿔도 될까요?

네! 수정하겠습니다

2024-02-02 08:41 UTC, jaewoongs commented on src/components/atoms/FitLogo.tsx
> +      viewBox={`0 0 ${width} ${(width * 38) / 119}`}
좋은 의견인것같아요!

2024-02-04 10:46 UTC, seheon99 submitted a review, later dismissed

2024-02-04 11:49 UTC, merged