유저 데이터 정보가 새로고침 시 사라지는 버그 수정
Team-Crops/fit-web pull request #93
Opened 2024-05-22 16:16 UTC by jaewoongs

### 변경 개요
새로고침 시 auth store의 정보가 사라짐
token이 있는 상태를 확인하고 다시 user 정보를 가져오는 방법으로 하려다가 그러면 시간이 오래걸려서 로그인이 안된것처럼 보일 때가 순간 있음
그래서 store 정보를 새로고침해도 유지하는 방향으로 수정했음

### 구현 내용
- auth store에 persist 추가
- header 로그인 확인 부분 token으로 확인하게 수정

### 관련 이슈
resolved: #88

2024-05-22 18:13 UTC, seheon99 commented on src/components/templates/LoginCallback.tsx
> -        router.replace('/');
P2: `router.replace` 를 사용하는게 성능상 유리한 것 같은데 변경한 이유가 있나요??

https://github.com/vercel/next.js/discussions/38400

2024-05-22 18:16 UTC, seheon99 commented
아까 카톡으로 말한 유저 로딩 문제는 `login-guard` 에서 처리가 될 것 같아요 따로 작업 안해도 될듯!

https://github.com/Team-Crops/fit-web/blob/c80782f3c9f606294da4208f23f27e17bc1ac21d/src/app/login-guard.tsx#L29-L47

2024-05-23 05:37 UTC, jaewoongs commented on src/components/templates/LoginCallback.tsx
> -        router.replace('/');
`router.replace`를 사용하는게 성능상 좋긴한데 로그인 후 새로고침이 필요해서 location.href로 수정했던 것이였습니다. 근데 이번에 방식을 바꾸면서 다시 router.replace로 수정하겠습니다!

2024-05-23 06:08 UTC, seheon99 requested changes

2024-05-23 06:08 UTC, seheon99 commented on src/components/templates/LoginCallback.tsx
> -        router.replace('/');
P1: 로그인 콜백 페이지로 돌아오면 안되니까 `replace` 가 좋을듯!

2024-05-23 09:16 UTC, seheon99 approved these changes

2024-05-23 09:16 UTC, merged