첫 회원가입 사용 가능한 툴에서 position 잘리는 문제 해결
Team-Crops/fit-web pull request #99
Opened 2024-05-23 10:57 UTC by jaewoongs

### 변경 개요
<img width="1624" alt="image" src="https://github.com/Team-Crops/fit-web/assets/58589176/5f58b423-46db-40f6-8bb2-04d38514a776">
첫 회원가입에서 포지션 오른쪽 짤리는 문제 

### 구현 내용
- 포지션 짤리는 부분 `overflow-x: auto`추가

### 관련 이슈
resolved: #98

2024-05-23 18:56 UTC, seheon99 requested changes
변경사항이 안보여요!!

2024-05-24 04:59 UTC, jaewoongs commented on src/components/organisms/sign-up/ToolAvailabilitySubmission.tsx
>    overflow-x: auto;
이거 추가한건데 왜 이렇게 나오지?? ㅋㅋㅋㅋㅋ

2024-05-24 05:35 UTC, seheon99 commented on src/components/organisms/sign-up/ToolAvailabilitySubmission.tsx
>    overflow-x: auto;
`dev` 에 `overflow-x: scroll` 코드가 있었나봐

2024-05-24 05:38 UTC, seheon99 approved these changes

2024-05-24 05:38 UTC, merged